"""Nombres y apellidos hispanos frecuentes (dato público, sin PII)."""

NOMBRES: frozenset[str] = frozenset({
    "adrian", "adriana", "agustin", "alberto", "alejandra", "alejandro", "alexandra",
    "alfonso", "alfredo", "alicia", "ana", "andres", "angel", "angela", "angelica",
    "antonio", "armando", "arturo", "aurora", "beatriz", "blanca", "camila", "carlos",
    "carmen", "carolina", "catalina", "cecilia", "cesar", "claudia", "claudio",
    "cristian", "cristina", "daniel", "daniela", "david", "diana", "diego", "dolores",
    "edgar", "eduardo", "elena", "elias", "elizabeth", "emilio", "enrique", "ernesto",
    "esperanza", "esteban", "esther", "eugenia", "eva", "fabian", "fabio", "fabiola",
    "felipe", "fernando", "flor", "francisca", "francisco", "gabriel", "gabriela",
    "gerardo", "german", "gilberto", "gloria", "gonzalo", "grace", "graciela",
    "guillermo", "gustavo", "hector", "helena", "henry", "hernan", "hilda", "hugo",
    "ignacio", "ines", "irene", "isabel", "isabella", "ivan", "jacinto", "jaime",
    "javier", "jennifer", "jesus", "joaquin", "jorge", "jose", "juan", "juana",
    "julia", "julian", "juliana", "julio", "karen", "karina", "laura", "leandro",
    "leonardo", "liliana", "lina", "lorena", "lucia", "luis", "luisa", "luz",
    "manuel", "marcela", "marco", "margarita", "maria", "mariana", "mariano",
    "mariela", "mario", "marta", "martin", "mateo", "mauricio", "mercedes",
    "miguel", "milena", "monica", "nancy", "natalia", "nicolas", "nora", "octavio",
    "olga", "oscar", "pablo", "patricia", "paula", "pedro", "pilar", "rafael",
    "ramon", "raquel", "ricardo", "roberto", "rocio", "rodolfo", "rodrigo", "rosa",
    "ruben", "ruth", "salvador", "samuel", "sandra", "santiago", "sara", "sebastian",
    "sergio", "silvia", "simon", "sofia", "sonia", "susana", "tatiana", "teresa",
    "tomas", "valentina", "vanessa", "veronica", "victor", "victoria", "walter",
    "wilson", "ximena", "yolanda", "yuli", "yurani",
})

APELLIDOS: frozenset[str] = frozenset({
    "acevedo", "aguilar", "alvarado", "alvarez", "amaya", "arango", "arboleda",
    "ariza", "avila", "barrios", "barrera", "bedoya", "beltran", "benitez", "bermudez",
    "blanco", "bonilla", "botero", "bravo", "bustamante", "cabrera", "cadena", "cardenas",
    "carrillo", "castano", "castro", "ceballos", "celis", "cifuentes", "contreras",
    "cordoba", "correa", "cortes", "duque", "escobar", "espinosa", "estrada", "fajardo", "fernandez",
    "figueroa", "florez", "franco", "galindo", "gallego", "garcia", "gaviria", "giraldo",
    "gomez", "gonzalez", "grajales", "gutierrez", "henao", "heredia", "herrera", "hoyos",
    "hoyos", "ibanez", "jimenez", "lara", "leon", "linares", "londoño", "lopez", "luna",
    "machado", "manrique", "marin", "marquez", "martinez", "medina", "mejia", "mendoza",
    "miranda", "molina", "moncada", "monroy", "montoya", "morales", "moreno", "mosquera",
    "munera", "munoz", "murillo", "naranjo", "nieto", "nino", "nunez", "ocampo", "olarte",
    "oliveros", "ordonez", "orozco", "ortega", "ortiz", "osorio", "osuna", "paez", "palacio",
    "palacios", "parra", "patiño", "perez", "pineda", "pinzon", "pizarro", "posada",
    "prieto", "quintero", "ramirez", "ramos", "restrepo", "reyes", "rico", "rincon",
    "rivera", "robles", "rodriguez", "rojas", "roldan", "romero", "rueda", "ruiz", "salazar",
    "salcedo", "sanchez", "sandoval", "santamaria", "santiago", "sarmiento", "segura",
    "sierra", "silva", "solis", "soto", "suarez", "tamayo", "tapia", "toro", "torres",
    "trujillo", "uribe", "valencia", "valenzuela", "vargas", "vanegas", "vasquez", "vega", "velasquez",
    "velazquez", "vergara", "villa", "villalba", "villamizar", "villanueva", "villarreal",
    "zapata", "zuluaga",
})
